# permissions for end users to view dockermachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockermachine-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - dockermachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - dockermachines/status
  verbs:
  - get
