apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: DockerMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: dockermachinetemplate
    app.kubernetes.io/instance: dockermachinetemplate-sample
    app.kubernetes.io/part-of: cluster-api-provider-docker
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-docker
  name: dockermachinetemplate-sample
spec:
  # TODO(user): Add fields here
